config/routes.rb
# frozen_string_literal: tru

Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  resources :deposits, only: %i[index new create]
  resources :withdrows, only: %i[index new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deposit.rb
# frozen_string_literal: true

require_relative '../operations/send_transaction'

class Deposit < ApplicationRecord
  belongs_to :user

  validates :from, presence: true
  validates :amount, presence: true
  validate :from_is_address

  before_create :send_transaction

  private

  def from_is_address
    formatter = Ethereum::Formatter.new
    message = 'must be an Ethereum address'
    errors.add(:from, message) unless formatter.valid_address?(from)
  end

  def send_transaction
    password = User.where(wallet: from).first.email
    self.hex = Operations::SendTransaction.new(
      from,
      user.wallet,
      amount,
      password
    ).call
  end
end

app/models/user.rb
# frozen_string_literal: true

require_relative '../services/node_api/personal'

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :deposits
  has_many :withdrows

  after_create :create_wallet

  private

  def create_wallet
    node = Services::NodeApi::Personal.new
    self.wallet = node.new_account(email)
    save
  end
end

app/models/withdrow.rb
# frozen_string_literal: true

require_relative '../operations/send_transaction'

class Withdrow < ApplicationRecord
  belongs_to :user

  validates :to, presence: true
  validates :amount, presence: true
  validate :to_is_address

  before_create :send_transaction

  private

  def to_is_address
    formatter = Ethereum::Formatter.new
    message = 'must be an Ethereum address'
    errors.add(:to, message) unless formatter.valid_address?(to)
  end

  def send_transaction
    password = user.email
    self.hex = Operations::SendTransaction.new(
      user.wallet,
      to,
      amount,
      password
    ).call
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/deposits_controller.rb
# frozen_string_literal: true

require_relative '../operations/create_deposit'

class DepositsController < ApplicationController
  before_action :authenticate_user!

  def index
    @deposits = current_user.deposits
  end

  def create
    operation_params = deposit_params(params)
    operation_params[:user] = current_user
    result = Operations::CreateDeposit.new(operation_params).call
    case result.first
    when :ok
      flash[:notice] = result.last
      redirect_to deposits_path
    when :error
      @deposit = result.last
      render :new
    end
  end

  def new
    @deposit = Deposit.new
  end

  private

  def deposit_params(params)
    params.require(:deposit).permit(:from, :amount)
  end
end

app/controllers/home_controller.rb
require_relative '../services/node_api/eth'

class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @balance = get_balance(@user.wallet)
  end

  private

  def get_balance(wallet)
    balance = Services::NodeApi::Eth.new.get_balance(wallet)
    formatter = Ethereum::Formatter.new
    formatter.from_wei(balance.to_i(16))
  end
end

app/controllers/withdrows_controller.rb
# frozen_string_literal: true

require_relative '../operations/create_withdrow'

class WithdrowsController < ApplicationController
  before_action :authenticate_user!

  def index
    @withdrows = current_user.withdrows
  end

  def new
    @withdrow = Withdrow.new
  end

  def create
    operation_params = withdrow_params(params)
    operation_params[:user] = current_user
    result = Operations::CreateWithdrow.new(operation_params).call
    case result.first
    when :ok
      flash[:notice] = result.last
      redirect_to withdrows_path
    when :error
      @withdrow = result.last
      render :new
    end
  end

  private

  def withdrow_params(params)
    params.require(:withdrow).permit(:to, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/withdrows_helper.rb
module WithdrowsHelper
end

app/views/deposits/index.html.slim
h1 Deposits

- if @deposits.count == 0
  p You have no deposits now
- else
  - @deposits.each do |deposit|
    | from: #{deposit.from}, amount: #{deposit.amount}
    br

== link_to 'New deposit', new_deposit_path

app/views/deposits/new.html.slim
h1 New Deposit
p * At the same time transactions work only from this node accounts

== form_for @deposit, url: { action: 'create' } do |f|
  - if @deposit.errors.any?
    #error_explanation
      h2 #{pluralize(@deposit.errors.count, "error")} prohibited this deposit from being saved:
      ul
        - @deposit.errors.full_messages.each do |message|
          li #{message}

  == f.label :from
  == f.text_field :from
  br
  == f.label :amount
  == f.text_field :amount
  p amount must looks like 1 eth or 0.0001
  br
  == f.submit 'Create'

app/views/home/index.html.slim
h1 My Ether Wallet for ROPSTEN

p email: #{@user.email}
p wallet: #{@user.wallet}
p ballance: #{@balance} eth

== link_to 'Deposits', deposits_path
br
== link_to 'Withdrows', withdrows_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyEtherWallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= link_to('Home', root_path) unless current_page?(root_path) %>
    <%= yield %>
  </body>
</html>

app/views/withdrows/index.html.slim
h1 Withdrows

- if @withdrows.count == 0
  p You have no withdrows now
- else
  - @withdrows.each do |withdrow|
    | to: #{withdrow.to}, amount: #{withdrow.amount}
    br

== link_to 'New withdrow', new_withdrow_path

app/views/withdrows/new.html.slim
h1 New Withdrow

== form_for @withdrow, url: { action: 'create' } do |f|
  - if @withdrow.errors.any?
    #error_explanation
      h2 #{pluralize(@withdrow.errors.count, "error")} prohibited this Withdrow from being saved:
      ul
        - @withdrow.errors.full_messages.each do |message|
          li #{message}

  == f.label :to
  == f.text_field :to
  br
  == f.label :amount
  == f.text_field :amount
  p amount must looks like 1 eth or 0.0001
  br
  == f.submit 'Create'